### ISSUE TITLE
Blocking Microsoft store via GPO not working

### ISSUE THREAD

**Issue by maxilampert** [The-Virtual-Desktop-Team/Virtual-Desktop-Optimization-Tool#45] opened 2021-02-24 00:48 UTC
Disabling the Microsoft store via GPO is not possible the store is always accessible and the "Microsoft Store is blocked" is not shown. 
Testing revealed that the "Microsoft Store Install Service" (InstallService) service must be able to start(set at least to manual(original setting), instead of disabled) for the GPO to work and be applied properly.

**Comment by sandude-ms** [comment] 2021-04-15 15:06
Hello @maxilampert,

We just merged in the change you requested, into the "main" branch.  If you can get a chance to test, let us know the result.

Thanks,

Robert M. Smith

**Comment by sandude-ms** [comment] 2021-05-14 19:03
We are closing this issue at this time, as we believe the issue is resolved.  If that turns out not to be case, please open a new issue and reference this issue.  Thank you for using the VDOT tool.

**Closed by sandude-ms** 2021-05-14 19:03 UTC
Labels: Under Review
