### ISSUE TITLE
Some DefaultUserSettings fail due to missing regkey

### ISSUE THREAD

**Issue by beek0084** [The-Virtual-Desktop-Team/Virtual-Desktop-Optimization-Tool#48] opened 2021-03-15 14:11 UTC
The new optimization script version that uses 'Set-ItemProperty' in stead of 'reg add' fails to set a couple of DefaultUserSettings  when using a Windows 10 multi-session 20H1 O365 (MicrosoftWindowsDesktop:office-365:20h1-evd-o365pp) gallery image because the registry keys do not exist.

I was able to workaround this issue by adding a couple of explicit 'new-item' lines to create the missing regkeys. It would be great if you could add an if statement in the loop to check if the registry keys exists and create it using new-item.

For the record. I needed to add these to get it working:
New-Item -Path HKLM:\DEFAULT\Software\Microsoft\Windows\CurrentVersion\Explorer -Name VisualEffects -Force | Out-Null
New-Item -Path HKLM:\DEFAULT\Software\Microsoft\Windows\CurrentVersion\StorageSense\Parameters -Name StoragePolicy -Force | Out-Null
New-Item -Path HKLM:\DEFAULT\Software\Microsoft\Windows\CurrentVersion\BackgroundAccessApplications -Name Microsoft.Windows.Photos_8wekyb3d8bbwe -Force | Out-Null
New-Item -Path HKLM:\DEFAULT\Software\Microsoft\Windows\CurrentVersion\BackgroundAccessApplications -Name Microsoft.SkypeApp_kzf8qxf38zg5c -Force | Out-Null
New-Item -Path HKLM:\DEFAULT\Software\Microsoft\Windows\CurrentVersion\BackgroundAccessApplications -Name Microsoft.YourPhone_8wekyb3d8bbwe -Force | Out-Null
New-Item -Path HKLM:\DEFAULT\Software\Microsoft\Windows\CurrentVersion\BackgroundAccessApplications -Name Microsoft.MicrosoftEdge_8wekyb3d8bbwe -Force | Out-Null
New-Item -Path HKLM:\DEFAULT\Software\Microsoft\Windows\CurrentVersion\BackgroundAccessApplications -Name Microsoft.549981C3F5F10_8wekyb3d8bbwe -Force | Out-Null
New-Item -Path HKLM:\DEFAULT\Software\Microsoft\Windows\CurrentVersion\UserProfileEngagement -Force | Out-Null
New-Item -Path HKLM:\DEFAULT\Software\Microsoft\Windows\CurrentVersion\SearchSettings -Force | Out-Null

Thanks for all the hard work!

**Comment by tmmuessig** [comment] 2021-03-15 15:29
Hi @beek0084,

Have not run across this, but in lines 235 through 246 we are checking to see if the key exists, and if not creating it.  Where specifically are you adding your New-Item? Knowing that might help me investigate it a little better.

Thanks.

**Comment by beek0084** [comment] 2021-03-15 15:58
Hi Tim, I might be mistaken but I believe you are checking if the _property_ exists, and if not creating it. The New-ItemProperty cmdlet does not create the registry key if its missing. 

The solution in this thread with a similar issue looks promising:
https://stackoverflow.com/questions/41884491/powershell-cant-update-a-registry-path-because-it-doesnt-exist-but-it-actual

This is how this region looks like in my working code right now:

`    # Apply appearance customizations to default user registry hive, then close hive file
    If ($DefaultUserSettings) {
        If (Test-Path .\ConfigurationFiles\DefaultUserSettings.json) {
            Write-Output ("[VDI Optimize] Set Default User Settings")
            $UserSettings = (Get-Content .\ConfigurationFiles\DefaultUserSettings.json | ConvertFrom-Json).Where( { $_.SetProperty -eq $true })
            If ($UserSettings.Count -gt 0) {
                REG LOAD HKLM\DEFAULT C:\Users\Default\NTUSER.DAT | Out-Null
                
                Write-Output ("Adding missing Registry Keys")
                New-Item -Path HKLM:\DEFAULT\Software\Microsoft\Windows\CurrentVersion\Explorer -Name VisualEffects -Force | Out-Null
                New-Item -Path HKLM:\DEFAULT\Software\Microsoft\Windows\CurrentVersion\StorageSense\Parameters -Name StoragePolicy -Force | Out-Null
                New-Item -Path HKLM:\DEFAULT\Software\Microsoft\Windows\CurrentVersion\BackgroundAccessApplications -Name Microsoft.Windows.Photos_8wekyb3d8bbwe -Force | Out-Null
                New-Item -Path HKLM:\DEFAULT\Software\Microsoft\Windows\CurrentVersion\BackgroundAccessApplications -Name Microsoft.SkypeApp_kzf8qxf38zg5c -Force | Out-Null
                New-Item -Path HKLM:\DEFAULT\Software\Microsoft\Windows\CurrentVersion\BackgroundAccessApplications -Name Microsoft.YourPhone_8wekyb3d8bbwe -Force | Out-Null
                New-Item -Path HKLM:\DEFAULT\Software\Microsoft\Windows\CurrentVersion\BackgroundAccessApplications -Name Microsoft.MicrosoftEdge_8wekyb3d8bbwe -Force | Out-Null
                New-Item -Path HKLM:\DEFAULT\Software\Microsoft\Windows\CurrentVersion\BackgroundAccessApplications -Name Microsoft.549981C3F5F10_8wekyb3d8bbwe -Force | Out-Null
                New-Item -Path HKLM:\DEFAULT\Software\Microsoft\Windows\CurrentVersion\UserProfileEngagement -Force | Out-Null
                New-Item -Path HKLM:\DEFAULT\Software\Microsoft\Windows\CurrentVersion\SearchSettings -Force | Out-Null

                Foreach ($Item in $UserSettings) {
                    If ($Item.PropertyType -eq "BINARY") { $Value = [byte[]]($Item.PropertyValue.Split(",")) }
                    Else { $Value = $Item.PropertyValue }
               
                    If (Test-Path -Path ("{0}" -f $Item.HivePath)) {
                        Write-Verbose ("Found {0}\{1}" -f $Item.HivePath,$Item.KeyName)
                        If (Get-ItemProperty -Path ("{0}" -f $Item.HivePath) -ErrorAction SilentlyContinue) { Set-ItemProperty -Path ("{0}" -f $Item.HivePath) -Name $Item.KeyName -Value $Value -Force }
                        Else { New-ItemProperty -Path ("{0}" -f $Item.HivePath) -Name $Item.KeyName -PropertyType $Item.PropertyType -Value $Value -Force | Out-Null }
                    }
                    Else {
                        Write-Warning ("Registry Path not found: {0}" -f $Item.HivePath)
                        Write-Verbose ("Creating new Registry Key")
                        $newKey = New-Item -Path ("{0}" -f $Item.HivePath) -Force
                        If (Test-Path -Path $newKey.PSPath) { New-ItemProperty -Path ("{0}" -f $Item.HivePath) -Name $Item.KeyName -PropertyType $Item.PropertyType -Value $Value -Force | Out-Null}
                        Else { Write-Output ("[ERROR] Failed to create new Registry key") }
                    }
                }

                & REG UNLOAD HKLM\DEFAULT | Out-Null
            }
            Else { Write-Warning ("No Default User Settings to set") }
        }
        Else { Write-Warning ("File not found: {0}\ConfigurationFiles\DefaultUserSettings.json" -f $WorkingLocation) }
    }
    #endregion
`

**Comment by tmmuessig** [comment] 2021-03-16 16:03
@beek0084  - We updated the JSON file, and it should be fixed now.  Give it another go and let us know if you have any more issues.  

Thanks

**Comment by robsmi-msfte** [comment] 2021-03-16 16:15
Hello @beek0084,

I just downloaded and deployed the UserSettings portion of the tool to a VM.  Then I went through and confirmed that all settings but 1 are being correctly applied, in the manner that we intended them to be.

The registry settings in the UserSettings file are not written to HKLM\Default.  During runtime, the tool loads the default user profile registry file (C:\Users\Default\NTUSER.DAT) to a temporary location called "DEFAULT" (results in HKLM\DEFAULT), and writes those settings to that registry file.  That file is the "template" file that is used for all subsequent user profiles created on the machine/device, from that point forward.  It does not affect user profiles that already exist.

**NOTE:** I just submitted a Pull Request to change the name we use when we load the default registry hive.  Using the name "DEFAULT", even temporarily, could be confusing, given that there is already a registry key called "HKEY_USERS\.DEFAULT".  Going forward, when we load that user profile hive, we will load it with the temporary name "HKLM\VDOT_TEMP".

The reason for this behavior, is that the tool was designed to be applied to new builds mainly.  This is also true where user profiles do not currently exist.  This tool could certainly be run on existing machines, though thorough testing is recommended to ensure the desired outcome.

What about existing user profiles?  If you want to apply the settings in the DefaultUser settings file to existing user profiles, there are a couple of ways to accomplish that.

- You could use group policy and set those settings as preferences
- You could create a PowerShell script to set those as a script for user logon.

Circling back to the one setting that didn't get set as we intended, that one is here:

HKEY_USERS\{SID}\SOFTWARE\Microsoft\Windows\CurrentVersion\ContentDeliveryManager
"SystemPaneSuggestionsEnabled"

I found a missing line that sets that property to true in that code block, so I added that back with a new Pull Request.

Check and see if the settings in your environment line up with what I have documented here.  To do that you would have to create a new user, add that user to the "Administrators" group (so that this user can run Sysdm.cpl and Regedit), then check if all the settings are as they should be, for the new user.

Thanks,

Robert M. Smith

**Closed** 2021-03-18 16:58 UTC

**Comment by beek0084** [comment] 2021-03-22 15:25
Works like charm! Thanks for the swift fix.
