### ISSUE TITLE
Diagnostic Policy Service (DPS) won't stop during VM Build on Windows 10 21H2 Multi-Session

### ISSUE THREAD

**Issue by brmcmill** [The-Virtual-Desktop-Team/Virtual-Desktop-Optimization-Tool#131] opened 2022-06-24 12:10 UTC
I recently ran the latest VDOT release on a Windows 10 21H2 Multi-Session Host + M365 Apps Marketplace Image within an Azure Virtual Desktop (AVD) environment and the DPS service would cease to stop.  We tested redeploying VDOT multiple times with the same result.  Unsure of the delta in the environment or if it's related to this Marketplace Image or something else.  I am happy to help troubleshoot this further.  We have an output file for VDOT when it's run during the session host build.  Screen below:

![image](https://user-images.githubusercontent.com/26752719/175531234-15428058-acde-450b-9ba2-26e82a0342ba.png)

**Comment by tmmuessig** [comment] 2022-06-27 15:46
I am not seeing any issues on a standard 21H2 image, but I am not using the same gallery image you are at the moment.

@robsmi-msfte - Do you have this environment up and running to test?

This is what I am currently getting for the DPS Service.

![image](https://user-images.githubusercontent.com/7741612/175980433-eaaf2ea5-420f-47b2-8db5-f72d3619780f.png)

**Comment by robsmi-msfte** [comment] 2022-06-27 22:05
It's not as important that the DPS service stops immediately, but whether the start service value is correctly set in the registry.  This is an example of an optimization setting not being fully implemented until after the restart.
I realize you most likely don't wait to take the reboot during a deployment, because this is just one of several tasks that are run installing and configuring things.
If you notice the service start value does not change, let us know and we will test with the same Marketplace offering and see what needs to be done.

**Comment by brmcmill** [comment] 2022-06-27 22:15
Thanks for the feedback, I'll test some more and provide more feedback.  Hope to have more time this week.

**Comment by tmmuessig** [comment] 2022-06-28 12:26
@brmcmill - Here is what we are thinking with regards to this issue.  Instead of trying to stop the services, we really just need to set the startup type to disabled (which is already happening in the code).  So for your testing, under the "Services" section comment out line ~407 `Stop-Service $Item.Name -Force -ErrorAction SilentlyContinue`.  This should resolve your issue at least while testing, but still set the service appropriately upon reboot.

We are currently testing this as well.

**Comment by robsmi-msfte** [comment] 2022-06-30 14:16
I just edited the PowerShell in "Windows_VDOT.ps1", commenting out the "Stop-Service" code.  The expected behavior is that the services listed in the .JSON file set to "Disabled", will have their start values set to "disabled".  The code will no longer attempt to stop the services.  The services will however continue to run until the next full restart.
These changes are in branch "DPSWork".  Please test if you can and report back with results.

**Comment by brmcmill** [comment] 2022-06-30 14:25
Thank you @robsmi-msfte  and @tmmuessig.  Will test soon and provide our results.  Thank you so much for your awesome support and quick turnaround!

**Comment by tmmuessig** [comment] 2022-07-12 15:13
We believe this issue to be resolved via Pull Request #135

**Closed by tmmuessig** 2022-07-12 15:13 UTC

**Comment by brmcmill** [comment] 2022-07-12 15:25
Hey @tmmuessig  -- apologies I didn't respond directly to this thread.  Testing was successful.  Thank you again you and @robsmi-msfte support.
